# Generated by Django 3.1.2 on 2022-03-14 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('epp_program', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EPPStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('cohort', models.CharField(blank=True, max_length=20, null=True)),
                ('teaching_field', models.CharField(max_length=50)),
                ('teaid', models.IntegerField(blank=True, null=True)),
                ('admission_offer_date', models.DateField(blank=True, null=True)),
                ('admission_acceptance_date', models.DateField(blank=True, null=True)),
                ('admission_date', models.DateField(blank=True, null=True)),
                ('admission_overall_gpa', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('admission_last60_gpa', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('subject_area_hours', models.IntegerField(blank=True, null=True)),
                ('subject_area_gpa', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('exit_status', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('exit_semester', models.CharField(blank=True, default='', max_length=5, null=True)),
                ('admission_reported_to_tea_date', models.DateField(blank=True, null=True)),
                ('admission_offer_letter', models.TextField(blank=True, null=True)),
                ('admission_acceptance_data', models.TextField(blank=True, null=True)),
                ('previous_degree', models.CharField(blank=True, max_length=10, null=True)),
                ('previous_degree_institution', models.CharField(blank=True, max_length=50, null=True)),
                ('previous_degree_date_month', models.IntegerField(blank=True, choices=[('', ''), (1, 'Jan'), (2, 'Feb'), (3, 'Mar'), (4, 'Apr'), (5, 'May'), (6, 'Jun'), (7, 'Jul'), (8, 'Aug'), (9, 'Sep'), (10, 'Oct'), (11, 'Nov'), (12, 'Dec')], null=True)),
                ('previous_degree_date_year', models.IntegerField(blank=True, null=True)),
                ('teaching_certificate_state', models.CharField(blank=True, max_length=2, null=True)),
                ('teaching_certificate_expiration', models.IntegerField(blank=True, null=True)),
                ('classroom_experience', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('additional_fields', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('admission_offered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eppstudent_offered_by_person', to='core.person')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.person')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='epp_program.eppprogram')),
            ],
        ),
    ]
