# Generated by Django 4.0.3 on 2022-03-30 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EPPProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=100)),
                ('program_abbreviation', models.CharField(max_length=20)),
                ('program_coordinator', models.CharField(max_length=50, null=True)),
                ('program_email', models.EmailField(max_length=50, null=True)),
                ('initial', models.BooleanField(default=True, help_text='Is this an initial teacher certification?')),
                ('route', models.CharField(default='trad', max_length=30)),
                ('has_teaching_fields', models.BooleanField(default=False)),
                ('admission_notification_text', models.TextField(blank=True, default='', help_text='E-mail template for admission offer notification')),
                ('auto_assigned_exams', models.TextField(blank=True, default='')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
