# Generated by Django 4.0.3 on 2022-04-01 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('student_placements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentplacements',
            name='student_email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterUniqueTogether(
            name='studentplacements',
            unique_together={('uin', 'semester')},
        ),
    ]
