# Generated by Django 4.0.3 on 2022-05-02 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('student_placements', '0003_studentplacements_semester_year'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentplacements',
            unique_together={('uin', 'semester', 'semester_year')},
        ),
    ]
