# Generated by Django 4.0.3 on 2022-03-30 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student_placements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateField()),
                ('notes', models.TextField(default='')),
                ('hours_submitted', models.PositiveIntegerField(default=0)),
                ('hours_approved', models.BooleanField()),
                ('approval_due_date', models.DateField()),
                ('semester', models.CharField(max_length=20)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('date_submitted', models.DateField(auto_now=True)),
                ('eppstudent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='student_placements.studentplacements')),
            ],
        ),
    ]
