# Generated by Django 4.0.3 on 2022-04-08 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelogs',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
