# Generated by Django 4.0.3 on 2022-03-31 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('time_logs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timelogs',
            name='student_placements',
        ),
    ]
