# Generated by Django 4.0.3 on 2022-04-10 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_logs', '0002_alter_timelogs_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelogs',
            name='hours_submitted',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=4),
        ),
    ]
