# Generated by Django 4.0.3 on 2022-04-01 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('time_logs', '0002_remove_timelogs_student_placements'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelogs',
            name='student_email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='timelogs',
            name='student_uin',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='person_uin', to='core.person', to_field='uin'),
        ),
    ]
