# Generated by Django 4.0.3 on 2022-04-01 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('time_logs', '0003_timelogs_student_email_alter_timelogs_student_uin'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timelogs',
            unique_together=set(),
        ),
    ]
