# Generated by Django 4.0.3 on 2022-04-01 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('time_logs', '0004_alter_timelogs_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timelogs',
            unique_together={('student_uin', 'log_date')},
        ),
    ]
