# Generated by Django 3.1.2 on 2022-03-14 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('person_id', models.AutoField(primary_key=True, serialize=False)),
                ('uin', models.PositiveIntegerField(blank=True, db_index=True, default=0, unique=True)),
                ('netid', models.CharField(blank=True, max_length=50)),
                ('campus', models.CharField(choices=[('CS', 'College Station'), ('GA', 'Galveston'), ('XX', 'Other')], default='CS', max_length=2)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('use_middle_name', models.BooleanField(default=False)),
                ('generation', models.CharField(blank=True, choices=[('SR', 'Sr.'), ('JR', 'Jr.'), ('III', 'III')], default='', max_length=3)),
                ('primary_email', models.EmailField(blank=True, max_length=254)),
                ('secondary_email', models.EmailField(blank=True, max_length=254)),
                ('primary_ethnicity', models.CharField(choices=[('A', 'Asian'), ('B', 'Black'), ('H', 'Hispanic'), ('I', 'I'), ('M', 'M'), ('N', 'N'), ('O', 'O'), ('T', 'T'), ('W', 'White'), ('X', 'Unknown')], default='X', max_length=1)),
                ('latino', models.BooleanField(default=False)),
                ('country_of_origin', models.CharField(blank=True, max_length=20)),
                ('sex', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('X', 'Unknown')], default='X', max_length=1)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, max_length=5000)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('last_login_ip', models.CharField(max_length=50, null=True)),
                ('last_updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.person')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
