# Generated by Django 3.1.2 on 2022-03-14 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authentication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uin', models.PositiveIntegerField(blank=True, db_index=True, default=0, unique=True)),
                ('netid', models.CharField(blank=True, max_length=50)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
    ]
